name: Build Android APK

on:
  workflow_dispatch:
    inputs:
      flavor:
        description: "Gradle product flavor (leave empty for default)"
        required: false
        default: ""
  push:
    branches:
      - main
    paths:
      - "lib/**"
      - "assets/**"
      - "pubspec.yaml"
      - "analysis_options.yaml"
      - "android/**"
      - ".github/workflows/build-apk.yml"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Install dependencies
        run: flutter pub get

      - name: Run static analysis
        run: flutter analyze

      - name: Run tests
        run: flutter test

      - name: Build APK
        env:
          FLAVOR: ${{ github.event.inputs.flavor }}
        run: |
          if [ -n "$FLAVOR" ]; then
            flutter build apk --flavor "$FLAVOR" --release
          else
            flutter build apk --release
          fi

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: build/app/outputs/flutter-apk/*.apk
          if-no-files-found: error
